#!/usr/bin/env bash
set -e

if [[ $(type -P "lovet") ]]; then
    export LOVET_WORKD=$HOME/../usr/lib/lovet
else
    export LOVET_WORKD=$(cd $(dirname $0) && pwd)
fi

case "$1" in
    create)
        "$LOVET_WORKD/commands/create"
	    ;;
    run)
        "$LOVET_WORKD/commands/run"
        ;;
    package)
        "$LOVET_WORKD/commands/package"
        ;;
    *)
        "$LOVET_WORKD/commands/help"
        ;;
esac
