#!/usr/bin/env bash
set -e
export LOVET_WORKD=$(cd $(dirname $0) && pwd)

case "$1" in
    create)
        "$LOVET_WORKD/commands/create"
	;;
    *)
        "$LOVET_WORKD/commands/help"
        ;;
esac
